using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;

namespace StringLocalizerGenerator
{
    [Generator]
    public class ResxLocalizerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Alle RESX-Dateien sammeln
            var resxFiles = context.AdditionalTextsProvider
                .Where(f => f.Path.EndsWith(".resx", StringComparison.OrdinalIgnoreCase))
                .Collect();

            // Für jede RESX-Datei Code generieren
            context.RegisterSourceOutput(resxFiles, (spc, resxFilesList) =>
            {
                foreach (var resxFile in resxFilesList)
                {
                    ProcessResxFile(spc, resxFile);
                }
            });
        }

        private void ProcessResxFile(SourceProductionContext spc, AdditionalText resxFile)
        {
            try
            {
                var fileName = Path.GetFileNameWithoutExtension(resxFile.Path);
                var content = resxFile.GetText()?.ToString();
                
                if (string.IsNullOrEmpty(content)) return;

                var doc = XDocument.Parse(content);
                var keys = doc.Descendants("data")
                    .Select(d => d.Attribute("name")?.Value)
                    .Where(name => !string.IsNullOrEmpty(name))
                    .ToList();

                if (!keys.Any()) return;

                // Properties generieren
                var properties = string.Join("\n", keys.Select(key =>
                    $"\t\t\tpublic string {key} => localizer[\"{key}\"].ToString();"
                ));

                // Für Shared.resx spezielle Behandlung
                string namespaceName = "TestApp";
                string className = fileName;
                string localizerType = fileName;

                if (fileName.Equals("Shared", StringComparison.OrdinalIgnoreCase))
                {
                    localizerType = "Shared";
                }

                var sourceCode = $$"""
                // <auto-generated />
                using Microsoft.Extensions.Localization;

                namespace {{namespaceName}}
                {
                    public static class {{className}}LocalizerExtensions
                    {
                        extension(IStringLocalizer<{{localizerType}}> localizer)
                        {
                            {{properties}}
                        }
                    }
                }
                """;

                spc.AddSource(
                    $"{className}LocalizerExtensions.g.cs",
                    SourceText.From(sourceCode, Encoding.UTF8)
                );
            }
            catch (Exception ex)
            {
                // Fehler melden
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "RSX001",
                        "Generator Error",
                        $"Error processing {resxFile.Path}: {ex.Message}",
                        "Localization",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
            }
        }
    }
}