using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;
using System.Xml.Linq;

namespace StringLocalizerGenerator
{
    [Generator]
    public class ResxLocalizerGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            // RESX-Datei finden
            var resxFile = context.AdditionalFiles
                .FirstOrDefault(f => f.Path.EndsWith("Shared.resx", StringComparison.OrdinalIgnoreCase));

            if (resxFile == null)
                return;

            // Inhalt lesen
            var resxContent = resxFile.GetText()?.ToString();
            if (string.IsNullOrEmpty(resxContent))
                return;

            // XML parsen
            var doc = XDocument.Parse(resxContent);

            // Alle Schlüssel extrahieren
            var keys = doc.Descendants("data")
                .Select(d => d.Attribute("name")?.Value)
                .Where(name => !string.IsNullOrEmpty(name))
                .ToList();

            if (!keys.Any())
                return;

            // Namespace finden
            var sharedType = context.Compilation.GetTypeByMetadataName("StringLocalizerTest.Shared");
            var namespaceName = sharedType?.ContainingNamespace?.ToString() ?? "StringLocalizerTest";

            // Properties generieren
            var properties = string.Join("\n", keys.Select(key =>
                $"    public string {key} => localizer[\"{key}\"].ToString();"
            ));

            // Code zusammenbauen
            var sourceCode = $@"
// <auto-generated />
using Microsoft.Extensions.Localization;
using {namespaceName};

public static class SharedLocalizerExtensions
{{
    extension(IStringLocalizer<Shared> localizer)
    {{
{properties}
    }}
}}
";

            // Code hinzufügen
            context.AddSource(
                "SharedLocalizerExtensions.g.cs",
                SourceText.From(sourceCode, Encoding.UTF8)
            );
        }
    }
}