//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JGUZDV.DynamicForms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JGUZDV.DynamicForms.Resources.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name ({0}) muss gesetzt sein.
        /// </summary>
        internal static string ChoiceOptions_Name {
            get {
                return ResourceManager.GetString("ChoiceOptions.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert muss gesetzt sein.
        /// </summary>
        internal static string ChoiceOptions_Value {
            get {
                return ResourceManager.GetString("ChoiceOptions.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung ({0}) muss gesetzt sein.
        /// </summary>
        internal static string FieldDefinition_Description {
            get {
                return ResourceManager.GetString("FieldDefinition.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikation muss gesetzt sein.
        /// </summary>
        internal static string FieldDefinition_Identifier {
            get {
                return ResourceManager.GetString("FieldDefinition.Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortierschlüssel muss positiv sein.
        /// </summary>
        internal static string FieldDefinition_SortKey {
            get {
                return ResourceManager.GetString("FieldDefinition.SortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label ({0}) muss gesetzt sein.
        /// </summary>
        internal static string InputDefinition_Label {
            get {
                return ResourceManager.GetString("InputDefinition.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ muss gesetzt sein.
        /// </summary>
        internal static string InputDefinition_Type {
            get {
                return ResourceManager.GetString("InputDefinition.Type", resourceCulture);
            }
        }
    }
}
