name: JGUZDV.AspNetCore.Logging

on: 
  pull_request:
    types:
      - opened
      - reopened
      - edited
    branches:
      - main
    paths:
      - '!**.md'

jobs:
  call-build-and-test:
    uses: ./.github/workflows/Build-and-Test.yml
    with:
      library-name: JGUZDV.AspNetCore.Logging
