name: JGUZDV.Extensions.Authorization

on:
  workflow_dispatch:
    inputs:
      push-to-nuget:
        description: Push package to NuGet
        type: boolean

  pull_request:
    branches:
      - main
    paths:
      - libraries/JGUZDV.Extensions.Authorization/**

jobs:
  call_default_build:
    uses: ./.github/workflows/default_build.yml
    with:
      library-name: JGUZDV.Extensions.Authorization
      push-to-nuget: ${{ inputs.push-to-nuget != '' && inputs.push-to-nuget }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}