//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JGUZDV.DynamicForms.Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComponentStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComponentStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JGUZDV.DynamicForms.Blazor.Resources.ComponentStrings", typeof(ComponentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgegebene Werte.
        /// </summary>
        internal static string EditFieldDefinition_ChoiceOptions {
            get {
                return ResourceManager.GetString("EditFieldDefinition.ChoiceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string EditFieldDefinition_Description {
            get {
                return ResourceManager.GetString("EditFieldDefinition.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikator.
        /// </summary>
        internal static string EditFieldDefinition_Identifier {
            get {
                return ResourceManager.GetString("EditFieldDefinition.Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabetyp.
        /// </summary>
        internal static string EditFieldDefinition_InputType {
            get {
                return ResourceManager.GetString("EditFieldDefinition.InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Liste.
        /// </summary>
        internal static string EditFieldDefinition_IsList {
            get {
                return ResourceManager.GetString("EditFieldDefinition.IsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erforderlich.
        /// </summary>
        internal static string EditFieldDefinition_IsRequired {
            get {
                return ResourceManager.GetString("EditFieldDefinition.IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string EditFieldDefinition_Label {
            get {
                return ResourceManager.GetString("EditFieldDefinition.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EditFieldDefinition_Name {
            get {
                return ResourceManager.GetString("EditFieldDefinition.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen.
        /// </summary>
        internal static string EditFieldDefinition_SelectType {
            get {
                return ResourceManager.GetString("EditFieldDefinition.SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortierschlüssel.
        /// </summary>
        internal static string EditFieldDefinition_SortKey {
            get {
                return ResourceManager.GetString("EditFieldDefinition.SortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datentyp.
        /// </summary>
        internal static string EditFieldDefinition_Type {
            get {
                return ResourceManager.GetString("EditFieldDefinition.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Wert.
        /// </summary>
        internal static string FieldInput_NoValues {
            get {
                return ResourceManager.GetString("FieldInput.NoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe konnte nicht in Zieltyp konvertiert werden.
        /// </summary>
        internal static string FieldInput_Validation_Convert {
            get {
                return ResourceManager.GetString("FieldInput.Validation.Convert", resourceCulture);
            }
        }
    }
}
